### ISSUE TITLE
Citations for dependencies

### ISSUE THREAD

**Issue by JohannesBuchner** [ThomasEdwardRiley/xpsi#14]
Dear all,

As you know, developing software is a underappreciated activity in astronomy research. The only reward we can obtain are citations. In the documentation, could you please encourage users to also cite the packages xpsi is built upon?
Here is an example I have used: https://johannesbuchner.github.io/BXA/#citing-bxa-correctly
pymultinest and multinest seem to be relevant in xpsi, and its users, for example https://arxiv.org/pdf/2104.06928.pdf . 

Cheers,
Johannes

**Comment by ThomasEdwardRiley** [comment]
Thanks, Johannes!

Guidelines added to documenation in patch v0.7.7: 93a17f7e80e55c7d03b94b0b1d4c797748701c4b.
